[project]
name = "kas-tac"
version = "0.1.0"
description = "KAS project for the Test-Automation-Controller (TAC)"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.4.0",
    "pre-commit-uv>=4.2.0",
]

[tool.uv]
link-mode = "copy"
